### ISSUE TITLE
Consider including well-formed examples

### ISSUE THREAD

**Issue by mloskot** [opengeospatial/2D-Tile-Matrix-Set#14]
It would be helpful if this repository included the JSON and XML examples of complete, self-contained and inter-linked, documents in JSON and XML encoding, e.g. those available at http://schemas.opengis.net/tms/1.0/json/examples/

**Comment by joanma747** [comment]
Good idea. 
Jerome examples added in the folder schemas/examples

**Comment by joanma747** [comment]
We need examples for both TMS and for TileSet metadata. Two folders?

https://github.com/opengeospatial/2D-Tile-Matrix-Set/tree/master/schemas/examples
