### ISSUE TITLE
Add the CDB Global Grid as a defined tile matrix set

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/2D-Tile-Matrix-Set#17]
The CDB Global Grid [combines the CDB Zones with the CDB Level of Details](https://docs.opengeospatial.org/is/15-113r5/15-113r5.html#CharacteristicsoftheCDBtilingstoragemodel) to define both using the 2DTMS Variable Width Tile Matrix Sets conformance class.
A definition is available here:
https://maps.ecere.com/ogcapi/tileMatrixSets/CDBGlobalGrid ([JSON](https://maps.ecere.com/ogcapi/tileMatrixSets/CDBGlobalGrid?f=json)).
It also provides an alternative practical example of variable width tile matrices.

Re-using the 2DTMS standard in CDB would greatly simplify understanding of these concepts.

**Comment by jerstlouis** [comment]
Applied in https://github.com/opengeospatial/2D-Tile-Matrix-Set/pull/19

**Comment by joanma747** [comment]
Changes applied by @jerstlouis
