### ISSUE TITLE
We need an Epoch in the tileSet metadata

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/2D-Tile-Matrix-Set#30]
Epoch is generally not part of the CRS.

**Comment by jerstlouis** [comment]
We do need an Epoch, and I believe the best place for it is in the TileSet metadata.
Possibly it should be added both at the top-level (along with a new `crs` property), as well as at the layer level.

We should probably also rename the layers'  `supportedCRS` to simply `crs` (it is a single value, not a list of supported CRS).

**Comment by joanma747** [comment]
Added to the model
![image](https://user-images.githubusercontent.com/5230444/120656556-01cef680-c484-11eb-91c4-351c07f14da7.png)

**Comment by cportele** [comment]
@joanma747 - the coordinate epoch is a decimal number (decimal year in the Gregorian calendar, for example, 2017-03-25 is 2017.23), not a string.

**Comment by joanma747** [comment]
Changed to "number" as suggested
