### ISSUE TITLE
Create a "registry" folder with the "master" copy for the "NA" to harvest.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/2D-Tile-Matrix-Set#37]
We  will create this folder with the "master" copy for the "NA" to harvest.

/registry/2.0/    with the json encoding following the 2D-TMS 2.0 encoding

a script could be create to translate the json into xml automatically.

The "2.0" subfolder will NOT be included by the "NA" urls and the "NA" will expose all versions of the encodings under a single URL and theoretically a "version=" parameter could be included in the future to return other versions.

**Comment by rob-metalinkage** [comment]
I have been experimenting with github actions - you should be able to set up a github action to automate running a script to generate XML, and probably to commit copies to a location on the OGC-NA NamingAuthority repos (or if that is hard to do have a workflow we can trigger on the NA repo to pull from this repo...)

see https://github.com/opengeospatial/NamingAuthority/blob/master/.github/workflows/entail_and_validate_changes.yml for how to set up a workflow that detects commit changes.

**Comment by joanma747** [comment]
We have created a \registry with all the TMS files that need to be created. I believe that finalizes this issue.
