### ISSUE TITLE
Other Admin Changes

### ISSUE THREAD

**Issue by ayoumans** [opengeospatial/2D-Tile-Matrix-Set#41]
Please look at Requirement #7, which is blank.  

Also, look at Annex D, there is a note on Web Mercator regarding NGA's stance.  The URL is not active.  Also, they (NGA) does allow Web Mercator for visualization, it is not recommended, but they have softened their stance somewhat.  It is still not allowed under CJCSI 3900.1 D, so now the US has conflicting guidance on Web Mercator....  :-)

**Comment by joanma747** [comment]
WE have fixed Requirement #7 and we have removed the non-active link. If a better recommendation for the text in the note is provided we will add it.
