### ISSUE TITLE
Include tileMatrixSetURI as a field in the /tileMatrixSets resource

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/2D-Tile-Matrix-Set#50]
**Day 3 of 2021-05 Sprint**

The /tileMatrixSets resource should provide information about the identity and the tileMatrixSetURI of the TMS.

The `id` does not need to match the `tileMatrixSetURI`.

If the TMS is registered in the Definitions Server, the tileMatrixSetURI should reference the TMS.

**Comment by joanma747** [comment]
Json and xml schemas are consisted with uml. Exclusive dependency of TileMAtrixSetURI on the OGC NA removed from UML and json and xml removed.
