### ISSUE TITLE
Change `geometryType` to `geometryDimension` integer

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/2D-Tile-Matrix-Set#56]
We decided to follow this approach in _OGC API - Styles_ ( https://github.com/opengeospatial/ogcapi-styles/issues/30 ) to avoid confusion with the Simple Features geometry types, which e.g. has single / multi flavors. We should re-synchronize the changes here.

> Change geometryType to geometryDimension (integer) with values: 0 (points), 1 (curves), 2 (surfaces), 3 (solids), null/not existent (mixed dimension/unknown)

**Comment by joanma747** [comment]
This is an easy change that avoid using confusing names (is a line a multilinestring?)
