### ISSUE TITLE
Make `dataType` an extensible list rather than a restricted enum

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/2D-Tile-Matrix-Set#57]
In JSON Schema, enums  are not extensible, but we foresee additional data types beyond `map`, `vector` and `coverage` and should not restrict these. Additional values are already being discussed for e.g. 3D models and point clouds.

In OGC API - Styles ( opengeospatial/ogcapi-styles#30 ) we changed the `enum` to `examples`.

> For dataType remove the enum and move the values to examples. This is not a final, definitive list. Add point cloud, mesh.

**Comment by joanma747** [comment]
Why about trying to create an open list by using oneOf(enum+string).

**Comment by jerstlouis** [comment]
@joanma747 We wanted to review the XML/XSD enum extensibility aspect for this before closing the issue, can we close it now at this stage?

**Comment by joanma747** [comment]
Fixed in the XSD schema
