### ISSUE TITLE
TMS WorldMercatorWGS84Quad.json issues

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/2D-Tile-Matrix-Set#6]
in http://schemas.opengis.net/tms/1.0/json/examples/WorldMercatorWGS84Quad.json

1. In addition to "tileHeight" : where there should be "tileMatrices" : (also, other VTP2 participants currently have tileMatrix, but I believe we had previously agreed this should be plural),
the topLeftCorner for each level should be e.g.

  [ -20037508.3427892439067, 20037508.3427892439067 ]

rather than

  [-180, 90],

(as it is in WebMercatorQuad, another projected CRS tiling scheme).

    http://ows.geo-solutions.it/geoserver/ogc/tiles/tileMatrixSets/WorldMercatorWGS84Quad?f=json
    https://services.interactive-instruments.de/t15/daraa/tileMatrixSets/WorldMercatorWGS84Quad?f=json

2. Also, the scales and the matrixWidth are all off by a factor of 2.

**Comment by jerstlouis** [comment]
Resolved by https://github.com/opengeospatial/2D-Tile-Matrix-Set/pull/19

**Comment by joanma747** [comment]
Changes applied by @jerstlouis
