### ISSUE TITLE
6.1.5 Reference to i dimension

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/2D-Tile-Matrix-Set#68]
As reported by Carl:

In [clause 6.1.5](https://docs.opengeospatial.org/DRAFTS/17-083r4.html#variable-matrixwidth-tile-matrix) is the sentence:

> The solution consists of reducing the number of tiles (matrixWidth) in the high latitude rows and generating those tiles with a compressed scale in the i dimension (see Figure 5).

Checking Figure 5, there is no reference (label) to the "i dimension".

And additional observations from myself:

Could we simply refer to the dimension as the "longitudinal dimension" or similar term to avoid confusion in 6.1.5?
Is this a result of Figure 5 that was updated, or shifted figure numbers and the reference should now be to Figure 7?

There are references to 3 discrete indices i, j, and tile matrix identifier in section [6.1.4](https://docs.opengeospatial.org/DRAFTS/17-083r4.html#tile-based-coordinates-in-a-tile-matrix-set) and in Figure 7. 

[6.1.4](https://docs.opengeospatial.org/DRAFTS/17-083r4.html#tile-based-coordinates-in-a-tile-matrix-set) also has this sentence:

> In a two-dimensional space, a **tile** is identified by 5 discrete indices that are named: tile row, tile column, tile matrix identifier, i and j. 

That doesn't sound right to me, a _tile_ can be identified only by the 3 indices tile matrix, tile row and tile column. Should this be saying _cell_ rather than tile?

In this 6.1.4 section, it seems that i and j are used for 2 completely different meanings:
- In the first bullet, i and j seem like coordinates inside a single tile
- In the second bullet, i and j seem like coordinates inside a whole tile matrix

Figure 7 seems to illustrate the first bullet with a) and the second with b), but the figure for b) calls coordinate _i'_ and _j'_.
It would be helpful to replace the bullets by a) and b) if that is the case, and be consistent about i vs. i'.

**Comment by joanma747** [comment]
Many figures link were broken and mentions to i and j were actualy to i' and j'. Fixed now.
