### ISSUE TITLE
Fix dependency URI in Clause 6.2.1

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/2D-Tile-Matrix-Set#70]
Clause 6.2.1 mentions a dependency http://www.opengis.net/spec/tile-model/1.0/req/tile-set-scheme

I think this URI was meant to be referencing the [Tile Set Scheme](https://docs.ogc.org/as/19-014r3/19-014r3.html#_requirement_class_tile_set_scheme) requirements class of the Abstract Specification Topic 22.

If that is the case, then the dependency URI in Clause 6.2.1 of the 2D TMS should be http://www.opengis.net/spec/2d-tile-model/1.0/req/tile-set-scheme

**Comment by joanma747** [comment]
Thanks for detecting this. fixed in the direction indicated.
