### ISSUE TITLE
Variable width conformance class is missing from Section 2 - Conformance

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/2D-Tile-Matrix-Set#75]
The following URIs should be listed in [_Section 2: conformance_](https://docs.opengeospatial.org/DRAFTS/17-083r4.html#_conformance):

- http://www.opengis.net/spec/tms/2.0/req/variablematrixwidth
- http://www.opengis.net/spec/tms/2.0/req/json-variablematrixwidth
- http://www.opengis.net/spec/tms/2.0/req/xml-variablematrixwidth

**Comment by joanma747** [comment]
Done. Thanks.
